### ISSUE TITLE
Typo in http.py

### ISSUE THREAD

**Issue by Roadsong** [jtpereyda/boofuzz-http#1]
Port 80 should be 26000 :)

**Comment by jtpereyda** [comment]
@Roadsong Thank you for opening an issue. If you want to fuzz boofuzz's HTTP server, then yes. :D But as a generic example, I think 80 makes enough sense since it's the IANA standard HTTP port.

**Comment by Roadsong** [comment]
Thanks for your reply and yes you are correct :D
